export default class CommonConstants{
  static readonly baidufanyi_base_url= "http://api.fanyi.baidu.com/api/trans/vip/translate?"



  static readonly API_HOST = "https://toolkit.diegodad.com/"
  static readonly WEB_HOST = "https://toolkit.diegodad.com/"

  static readonly VIDEO_HTTPS_LISTS: Array<string> = [
    'http://1251017968.vod2.myqcloud.com/3eb04eefvodtransgzp1251017968/8782b1285285890810009576163/v.f30.mp4',
    'https://video.chinanews.com/flv/2019/04/23/400/111773_web.mp4',
    'https://assets.mixkit.co/videos/preview/mixkit-white-cat-lying-among-the-grasses-seen-up-close-22732-large.mp4']

}